// Copyright 2025, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // ainshrpc.AIAttachedFile
    type AIAttachedFile = {
        name: string;
        type: string;
        size: number;
        data64: string;
    };

    // ainconfig.AIModeConfigType
    type AIModeConfigType = {
        "display:name": string;
        "display:order"?: number;
        "display:icon"?: string;
        "display:description"?: string;
        "ai:provider"?: string;
        "ai:apitype"?: string;
        "ai:model"?: string;
        "ai:thinkinglevel"?: string;
        "ai:endpoint"?: string;
        "ai:azureapiversion"?: string;
        "ai:apitoken"?: string;
        "ai:apitokensecretname"?: string;
        "ai:azureresourcename"?: string;
        "ai:azuredeployment"?: string;
        "ai:capabilities"?: string[];
        "ai:switchcompat"?: string[];
        "waveai:cloud"?: boolean;
        "waveai:premium"?: boolean;
        "ainai:cloud"?: boolean;
        "ainai:premium"?: boolean;
    };

    // ainconfig.AIModeConfigUpdate
    type AIModeConfigUpdate = {
        configs: {[key: string]: AIModeConfigType};
    };

    // ainshrpc.ActivityDisplayType
    type ActivityDisplayType = {
        width: number;
        height: number;
        dpr: number;
        internal?: boolean;
    };

    // ainshrpc.ActivityUpdate
    type ActivityUpdate = {
        fgminutes?: number;
        activeminutes?: number;
        openminutes?: number;
        waveaifgminutes?: number;
        waveaiactiveminutes?: number;
        numtabs?: number;
        newtab?: number;
        numblocks?: number;
        numwindows?: number;
        numws?: number;
        numwsnamed?: number;
        numsshconn?: number;
        numwslconn?: number;
        nummagnify?: number;
        termcommandsrun?: number;
        numpanics?: number;
        numaireqs?: number;
        startup?: number;
        shutdown?: number;
        settabtheme?: number;
        buildtime?: string;
        displays?: ActivityDisplayType[];
        renderers?: {[key: string]: number};
        blocks?: {[key: string]: number};
        wshcmds?: {[key: string]: number};
        conn?: {[key: string]: number};
    };

    // ainshrpc.AiMessageData
    type AiMessageData = {
        message?: string;
    };

    // ainshrpc.AppInfo
    type AppInfo = {
        appid: string;
        modtime: number;
        manifest?: AppManifest;
    };

    // ainshrpc.AppManifest
    type AppManifest = {
        appmeta: AppMeta;
        configschema: {[key: string]: any};
        dataschema: {[key: string]: any};
        secrets: {[key: string]: SecretMeta};
    };

    // ainshrpc.AppMeta
    type AppMeta = {
        title: string;
        shortdesc: string;
        icon: string;
        iconcolor: string;
    };

    // ainobj.Block
    type Block = WaveObj & {
        parentoref?: string;
        runtimeopts?: RuntimeOpts;
        stickers?: StickerType[];
        subblockids?: string[];
    };

    // blockcontroller.BlockControllerRuntimeStatus
    type BlockControllerRuntimeStatus = {
        blockid: string;
        version: number;
        shellprocstatus?: string;
        shellprocconnname?: string;
        shellprocexitcode: number;
        tsunamiport?: number;
    };

    // ainobj.BlockDef
    type BlockDef = {
        files?: {[key: string]: FileDef};
        meta?: MetaType;
    };

    // ainshrpc.BlockInfoData
    type BlockInfoData = {
        blockid: string;
        tabid: string;
        workspaceid: string;
        block: Block;
        files: FileInfo[];
    };

    // webcmd.BlockInputWSCommand
    type BlockInputWSCommand = {
        wscommand: "blockinput";
        blockid: string;
        inputdata64: string;
    };

    // ainshrpc.BlocksListEntry
    type BlocksListEntry = {
        windowid: string;
        workspaceid: string;
        tabid: string;
        blockid: string;
        meta: MetaType;
    };

    // ainshrpc.BlocksListRequest
    type BlocksListRequest = {
        windowid?: string;
        workspaceid?: string;
    };

    // ainshrpc.BuilderStatusData
    type BuilderStatusData = {
        status: string;
        port?: number;
        exitcode?: number;
        errormsg?: string;
        version: number;
        manifest?: AppManifest;
        secretbindings?: {[key: string]: string};
        secretbindingscomplete: boolean;
    };

    // ainobj.Client
    type Client = WaveObj & {
        windowids: string[];
        tosagreed?: number;
        hasoldhistory?: boolean;
        tempoid?: string;
    };

    // workspaceservice.CloseTabRtnType
    type CloseTabRtnType = {
        closewindow?: boolean;
        newactivetabid?: string;
    };

    // ainshrpc.CommandAppendIJsonData
    type CommandAppendIJsonData = {
        zoneid: string;
        filename: string;
        data: {[key: string]: any};
    };

    // ainshrpc.CommandAuthenticateRtnData
    type CommandAuthenticateRtnData = {
        env?: {[key: string]: string};
        initscripttext?: string;
        rpccontext?: RpcContext;
    };

    // ainshrpc.CommandAuthenticateTokenData
    type CommandAuthenticateTokenData = {
        token: string;
    };

    // ainshrpc.CommandBlockInputData
    type CommandBlockInputData = {
        blockid: string;
        inputdata64?: string;
        signame?: string;
        termsize?: TermSize;
    };

    // ainshrpc.CommandCaptureBlockScreenshotData
    type CommandCaptureBlockScreenshotData = {
        blockid: string;
    };

    // ainshrpc.CommandCheckGoVersionRtnData
    type CommandCheckGoVersionRtnData = {
        gostatus: string;
        gopath: string;
        goversion: string;
        errorstring?: string;
    };

    // ainshrpc.CommandControllerAppendOutputData
    type CommandControllerAppendOutputData = {
        blockid: string;
        data64: string;
    };

    // ainshrpc.CommandControllerResyncData
    type CommandControllerResyncData = {
        forcerestart?: boolean;
        tabid: string;
        blockid: string;
        rtopts?: RuntimeOpts;
    };

    // ainshrpc.CommandCreateBlockData
    type CommandCreateBlockData = {
        tabid: string;
        blockdef: BlockDef;
        rtopts?: RuntimeOpts;
        magnified?: boolean;
        ephemeral?: boolean;
        focused?: boolean;
        targetblockid?: string;
        targetaction?: string;
    };

    // ainshrpc.CommandCreateSubBlockData
    type CommandCreateSubBlockData = {
        parentblockid: string;
        blockdef: BlockDef;
    };

    // ainshrpc.CommandDeleteAppFileData
    type CommandDeleteAppFileData = {
        appid: string;
        filename: string;
    };

    // ainshrpc.CommandDeleteBlockData
    type CommandDeleteBlockData = {
        blockid: string;
    };

    // ainshrpc.CommandDeleteFileData
    type CommandDeleteFileData = {
        path: string;
        recursive: boolean;
    };

    // ainshrpc.CommandDisposeData
    type CommandDisposeData = {
        routeid: string;
    };

    // ainshrpc.CommandElectronDecryptData
    type CommandElectronDecryptData = {
        ciphertext: string;
    };

    // ainshrpc.CommandElectronDecryptRtnData
    type CommandElectronDecryptRtnData = {
        plaintext: string;
        storagebackend: string;
    };

    // ainshrpc.CommandElectronEncryptData
    type CommandElectronEncryptData = {
        plaintext: string;
    };

    // ainshrpc.CommandElectronEncryptRtnData
    type CommandElectronEncryptRtnData = {
        ciphertext: string;
        storagebackend: string;
    };

    // ainshrpc.CommandEventReadHistoryData
    type CommandEventReadHistoryData = {
        event: string;
        scope: string;
        maxitems: number;
    };

    // ainshrpc.CommandFileCopyData
    type CommandFileCopyData = {
        srcuri: string;
        desturi: string;
        opts?: FileCopyOpts;
    };

    // ainshrpc.CommandFileRestoreBackupData
    type CommandFileRestoreBackupData = {
        backupfilepath: string;
        restoretofilename: string;
    };

    // ainshrpc.CommandGetMetaData
    type CommandGetMetaData = {
        oref: ORef;
    };

    // ainshrpc.CommandGetRTInfoData
    type CommandGetRTInfoData = {
        oref: ORef;
    };

    // ainshrpc.CommandGetTempDirData
    type CommandGetTempDirData = {
        filename?: string;
    };

    // ainshrpc.CommandGetWaveAIChatData
    type CommandGetWaveAIChatData = {
        chatid: string;
    };

    // ainshrpc.CommandListAllAppFilesData
    type CommandListAllAppFilesData = {
        appid: string;
    };

    // ainshrpc.CommandListAllAppFilesRtnData
    type CommandListAllAppFilesRtnData = {
        path: string;
        absolutepath: string;
        parentdir?: string;
        entries: DirEntryOut[];
        entrycount: number;
        totalentries: number;
        truncated?: boolean;
    };

    // ainshrpc.CommandMakeDraftFromLocalData
    type CommandMakeDraftFromLocalData = {
        localappid: string;
    };

    // ainshrpc.CommandMakeDraftFromLocalRtnData
    type CommandMakeDraftFromLocalRtnData = {
        draftappid: string;
    };

    // ainshrpc.CommandMessageData
    type CommandMessageData = {
        message: string;
    };

    // ainshrpc.CommandPublishAppData
    type CommandPublishAppData = {
        appid: string;
    };

    // ainshrpc.CommandPublishAppRtnData
    type CommandPublishAppRtnData = {
        publishedappid: string;
    };

    // ainshrpc.CommandReadAppFileData
    type CommandReadAppFileData = {
        appid: string;
        filename: string;
    };

    // ainshrpc.CommandReadAppFileRtnData
    type CommandReadAppFileRtnData = {
        data64: string;
        notfound?: boolean;
        modts?: number;
    };

    // ainshrpc.CommandRemoteListEntriesData
    type CommandRemoteListEntriesData = {
        path: string;
        opts?: FileListOpts;
    };

    // ainshrpc.CommandRemoteListEntriesRtnData
    type CommandRemoteListEntriesRtnData = {
        fileinfo?: FileInfo[];
    };

    // ainshrpc.CommandRemoteStreamFileData
    type CommandRemoteStreamFileData = {
        path: string;
        byterange?: string;
    };

    // ainshrpc.CommandRemoteStreamTarData
    type CommandRemoteStreamTarData = {
        path: string;
        opts?: FileCopyOpts;
    };

    // ainshrpc.CommandRenameAppFileData
    type CommandRenameAppFileData = {
        appid: string;
        fromfilename: string;
        tofilename: string;
    };

    // ainshrpc.CommandResolveIdsData
    type CommandResolveIdsData = {
        blockid: string;
        ids: string[];
    };

    // ainshrpc.CommandResolveIdsRtnData
    type CommandResolveIdsRtnData = {
        resolvedids: {[key: string]: ORef};
    };

    // ainshrpc.CommandRestartBuilderAndWaitData
    type CommandRestartBuilderAndWaitData = {
        builderid: string;
    };

    // ainshrpc.CommandSetMetaData
    type CommandSetMetaData = {
        oref: ORef;
        meta: MetaType;
    };

    // ainshrpc.CommandSetRTInfoData
    type CommandSetRTInfoData = {
        oref: ORef;
        data: ObjRTInfo;
        delete?: boolean;
    };

    // ainshrpc.CommandStartBuilderData
    type CommandStartBuilderData = {
        builderid: string;
    };

    // ainshrpc.CommandStreamAckData
    type CommandStreamAckData = {
        id: number;
        seq: number;
        rwnd: number;
        fin?: boolean;
        delay?: number;
        cancel?: boolean;
        error?: string;
    };

    // ainshrpc.CommandStreamData
    type CommandStreamData = {
        id: number;
        seq: number;
        data64?: string;
        eof?: boolean;
        error?: string;
    };

    // ainshrpc.CommandTermGetScrollbackLinesData
    type CommandTermGetScrollbackLinesData = {
        linestart: number;
        lineend: number;
        lastcommand: boolean;
    };

    // ainshrpc.CommandTermGetScrollbackLinesRtnData
    type CommandTermGetScrollbackLinesRtnData = {
        totallines: number;
        linestart: number;
        lines: string[];
        lastupdated: number;
    };

    // ainshrpc.CommandVarData
    type CommandVarData = {
        key: string;
        val?: string;
        remove?: boolean;
        zoneid: string;
        filename: string;
    };

    // ainshrpc.CommandVarResponseData
    type CommandVarResponseData = {
        key: string;
        val: string;
        exists: boolean;
    };

    // ainshrpc.CommandWaitForRouteData
    type CommandWaitForRouteData = {
        routeid: string;
        waitms: number;
    };

    // ainshrpc.CommandWaveAIAddContextData
    type CommandWaveAIAddContextData = {
        files?: AIAttachedFile[];
        text?: string;
        submit?: boolean;
        newchat?: boolean;
    };

    // ainshrpc.CommandWaveAIGetToolDiffData
    type CommandWaveAIGetToolDiffData = {
        chatid: string;
        toolcallid: string;
    };

    // ainshrpc.CommandWaveAIGetToolDiffRtnData
    type CommandWaveAIGetToolDiffRtnData = {
        originalcontents64: string;
        modifiedcontents64: string;
    };

    // ainshrpc.CommandWaveAIToolApproveData
    type CommandWaveAIToolApproveData = {
        toolcallid: string;
        approval?: string;
    };

    // ainshrpc.CommandWebSelectorData
    type CommandWebSelectorData = {
        workspaceid: string;
        blockid: string;
        tabid: string;
        selector: string;
        opts?: WebSelectorOpts;
    };

    // ainshrpc.CommandWriteAppFileData
    type CommandWriteAppFileData = {
        appid: string;
        filename: string;
        data64: string;
    };

    // ainshrpc.CommandWriteAppGoFileData
    type CommandWriteAppGoFileData = {
        appid: string;
        data64: string;
    };

    // ainshrpc.CommandWriteAppGoFileRtnData
    type CommandWriteAppGoFileRtnData = {
        data64: string;
    };

    // ainshrpc.CommandWriteAppSecretBindingsData
    type CommandWriteAppSecretBindingsData = {
        appid: string;
        bindings: {[key: string]: string};
    };

    // ainshrpc.CommandWriteTempFileData
    type CommandWriteTempFileData = {
        filename: string;
        data64: string;
    };

    // ainconfig.ConfigError
    type ConfigError = {
        file: string;
        err: string;
    };

    // ainshrpc.ConnConfigRequest
    type ConnConfigRequest = {
        host: string;
        metamaptype: MetaType;
    };

    // ainshrpc.ConnExtData
    type ConnExtData = {
        connname: string;
        logblockid?: string;
    };

    // ainconfig.ConnKeywords
    type ConnKeywords = {
        "conn:wshenabled"?: boolean;
        "conn:askbeforewshinstall"?: boolean;
        "conn:wshpath"?: string;
        "conn:shellpath"?: string;
        "conn:ignoresshconfig"?: boolean;
        "display:hidden"?: boolean;
        "display:order"?: number;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:theme"?: string;
        "cmd:env"?: {[key: string]: string};
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
        "ssh:user"?: string;
        "ssh:hostname"?: string;
        "ssh:port"?: string;
        "ssh:identityfile"?: string[];
        "ssh:passwordsecretname"?: string;
        "ssh:batchmode"?: boolean;
        "ssh:pubkeyauthentication"?: boolean;
        "ssh:passwordauthentication"?: boolean;
        "ssh:kbdinteractiveauthentication"?: boolean;
        "ssh:preferredauthentications"?: string[];
        "ssh:addkeystoagent"?: boolean;
        "ssh:identityagent"?: string;
        "ssh:identitiesonly"?: boolean;
        "ssh:proxyjump"?: string[];
        "ssh:userknownhostsfile"?: string[];
        "ssh:globalknownhostsfile"?: string[];
    };

    // ainshrpc.ConnRequest
    type ConnRequest = {
        host: string;
        keywords?: ConnKeywords;
        logblockid?: string;
    };

    // ainshrpc.ConnStatus
    type ConnStatus = {
        status: string;
        wshenabled: boolean;
        connection: string;
        connected: boolean;
        hasconnected: boolean;
        activeconnnum: number;
        error?: string;
        wsherror?: string;
        nowshreason?: string;
        wshversion?: string;
    };

    // ainshrpc.CpuDataRequest
    type CpuDataRequest = {
        id: string;
        count: number;
    };

    // ainshrpc.DirEntryOut
    type DirEntryOut = {
        name: string;
        dir?: boolean;
        symlink?: boolean;
        size?: number;
        mode: string;
        modified: string;
        modifiedtime: string;
    };

    // vdom.DomRect
    type DomRect = {
        top: number;
        left: number;
        right: number;
        bottom: number;
        width: number;
        height: number;
    };

    // ainshrpc.FetchSuggestionsData
    type FetchSuggestionsData = {
        suggestiontype: string;
        query: string;
        widgetid: string;
        reqnum: number;
        "file:cwd"?: string;
        "file:dironly"?: boolean;
        "file:connection"?: string;
    };

    // ainshrpc.FetchSuggestionsResponse
    type FetchSuggestionsResponse = {
        reqnum: number;
        suggestions: SuggestionType[];
    };

    // ainshrpc.FileCopyOpts
    type FileCopyOpts = {
        overwrite?: boolean;
        recursive?: boolean;
        merge?: boolean;
        timeout?: number;
    };

    // ainshrpc.FileData
    type FileData = {
        info?: FileInfo;
        data64?: string;
        entries?: FileInfo[];
        at?: FileDataAt;
    };

    // ainshrpc.FileDataAt
    type FileDataAt = {
        offset: number;
        size?: number;
    };

    // ainobj.FileDef
    type FileDef = {
        content?: string;
        meta?: {[key: string]: any};
    };

    // ainshrpc.FileInfo
    type FileInfo = {
        path: string;
        dir?: string;
        name?: string;
        notfound?: boolean;
        opts?: FileOpts;
        size?: number;
        meta?: {[key: string]: any};
        mode?: number;
        modestr?: string;
        modtime?: number;
        isdir?: boolean;
        supportsmkdir?: boolean;
        mimetype?: string;
        readonly?: boolean;
    };

    // ainshrpc.FileListData
    type FileListData = {
        path: string;
        opts?: FileListOpts;
    };

    // ainshrpc.FileListOpts
    type FileListOpts = {
        all?: boolean;
        offset?: number;
        limit?: number;
    };

    // ainshrpc.FileOpts
    type FileOpts = {
        maxsize?: number;
        circular?: boolean;
        ijson?: boolean;
        ijsonbudget?: number;
        truncate?: boolean;
        append?: boolean;
    };

    // ainshrpc.FileShareCapability
    type FileShareCapability = {
        canappend: boolean;
        canmkdir: boolean;
    };

    // ainconfig.FullConfigType
    type FullConfigType = {
        settings: SettingsType;
        mimetypes: {[key: string]: MimeTypeConfigType};
        defaultwidgets: {[key: string]: WidgetConfigType};
        widgets: {[key: string]: WidgetConfigType};
        presets: {[key: string]: MetaType};
        termthemes: {[key: string]: TermThemeType};
        connections: {[key: string]: ConnKeywords};
        bookmarks: {[key: string]: WebBookmark};
        waveai: {[key: string]: AIModeConfigType};
        ainai: {[key: string]: AIModeConfigType};
        configerrors: ConfigError[];
    };

    // ainobj.LayoutActionData
    type LayoutActionData = {
        actiontype: string;
        actionid: string;
        blockid: string;
        nodesize?: number;
        indexarr?: number[];
        focused: boolean;
        magnified: boolean;
        ephemeral: boolean;
        targetblockid?: string;
        position?: string;
    };

    // ainobj.LayoutState
    type LayoutState = WaveObj & {
        rootnode?: any;
        magnifiednodeid?: string;
        focusednodeid?: string;
        leaforder?: LeafOrderEntry[];
        pendingbackendactions?: LayoutActionData[];
    };

    // ainobj.LeafOrderEntry
    type LeafOrderEntry = {
        nodeid: string;
        blockid: string;
    };

    // ainobj.MetaTSType
    type MetaType = {
        view?: string;
        controller?: string;
        file?: string;
        url?: string;
        pinnedurl?: string;
        connection?: string;
        edit?: boolean;
        history?: string[];
        "history:forward"?: string[];
        "display:name"?: string;
        "display:order"?: number;
        icon?: string;
        "icon:color"?: string;
        "frame:*"?: boolean;
        frame?: boolean;
        "frame:bordercolor"?: string;
        "frame:activebordercolor"?: string;
        "frame:title"?: string;
        "frame:icon"?: string;
        "frame:text"?: string;
        "cmd:*"?: boolean;
        cmd?: string;
        "cmd:interactive"?: boolean;
        "cmd:login"?: boolean;
        "cmd:runonstart"?: boolean;
        "cmd:clearonstart"?: boolean;
        "cmd:runonce"?: boolean;
        "cmd:closeonexit"?: boolean;
        "cmd:closeonexitforce"?: boolean;
        "cmd:closeonexitdelay"?: number;
        "cmd:nowsh"?: boolean;
        "cmd:args"?: string[];
        "cmd:shell"?: boolean;
        "cmd:allowconnchange"?: boolean;
        "cmd:jwt"?: boolean;
        "cmd:env"?: {[key: string]: string};
        "cmd:cwd"?: string;
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
        "ai:*"?: boolean;
        "ai:preset"?: string;
        "ai:apitype"?: string;
        "ai:baseurl"?: string;
        "ai:apitoken"?: string;
        "ai:name"?: string;
        "ai:model"?: string;
        "ai:orgid"?: string;
        "ai:apiversion"?: string;
        "ai:maxtokens"?: number;
        "ai:timeoutms"?: number;
        "aifilediff:chatid"?: string;
        "aifilediff:toolcallid"?: string;
        "editor:*"?: boolean;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "graph:*"?: boolean;
        "graph:numpoints"?: number;
        "graph:metrics"?: string[];
        "sysinfo:type"?: string;
        "bg:*"?: boolean;
        bg?: string;
        "bg:opacity"?: number;
        "bg:blendmode"?: string;
        "bg:bordercolor"?: string;
        "bg:activebordercolor"?: string;
        "waveai:panelopen"?: boolean;
        "waveai:panelwidth"?: number;
        "waveai:model"?: string;
        "waveai:chatid"?: string;
        "waveai:widgetcontext"?: boolean;
        "ainai:panelopen"?: boolean;
        "ainai:panelwidth"?: number;
        "ainai:model"?: string;
        "ainai:chatid"?: string;
        "ainai:widgetcontext"?: boolean;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:mode"?: string;
        "term:theme"?: string;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:scrollback"?: number;
        "term:vdomblockid"?: string;
        "term:vdomtoolbarblockid"?: string;
        "term:transparency"?: number;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "term:conndebug"?: string;
        "web:zoom"?: number;
        "web:hidenav"?: boolean;
        "web:partition"?: string;
        "web:useragenttype"?: string;
        "markdown:fontsize"?: number;
        "markdown:fixedfontsize"?: number;
        "tsunami:*"?: boolean;
        "tsunami:sdkreplacepath"?: string;
        "tsunami:apppath"?: string;
        "tsunami:appid"?: string;
        "tsunami:scaffoldpath"?: string;
        "tsunami:env"?: {[key: string]: string};
        "vdom:*"?: boolean;
        "vdom:initialized"?: boolean;
        "vdom:correlationid"?: string;
        "vdom:route"?: string;
        "vdom:persist"?: boolean;
        "onboarding:githubstar"?: boolean;
        "onboarding:lastversion"?: string;
        count?: number;
    };

    // tsgenmeta.MethodMeta
    type MethodMeta = {
        Desc: string;
        ArgNames: string[];
        ReturnDesc: string;
    };

    // ainconfig.MimeTypeConfigType
    type MimeTypeConfigType = {
        icon: string;
        color: string;
    };

    // ainobj.ORef
    type ORef = string;

    // ainobj.ObjRTInfo
    type ObjRTInfo = {
        "tsunami:appmeta"?: AppMeta;
        "tsunami:schemas"?: any;
        "shell:hascurcwd"?: boolean;
        "shell:state"?: string;
        "shell:type"?: string;
        "shell:version"?: string;
        "shell:uname"?: string;
        "shell:integration"?: boolean;
        "shell:inputempty"?: boolean;
        "shell:lastcmd"?: string;
        "shell:lastcmdexitcode"?: number;
        "builder:layout"?: {[key: string]: number};
        "builder:appid"?: string;
        "builder:env"?: {[key: string]: string};
        "waveai:chatid"?: string;
        "waveai:mode"?: string;
        "waveai:maxoutputtokens"?: number;
        "ainai:chatid"?: string;
        "ainai:mode"?: string;
        "ainai:maxoutputtokens"?: number;
    };

    // iochantypes.Packet
    type Packet = {
        Data: string;
        Checksum: string;
    };

    // ainshrpc.PathCommandData
    type PathCommandData = {
        pathtype: string;
        open: boolean;
        openexternal: boolean;
        tabid: string;
    };

    // ainobj.Point
    type Point = {
        x: number;
        y: number;
    };

    // uctypes.RateLimitInfo
    type RateLimitInfo = {
        req: number;
        reqlimit: number;
        preq: number;
        preqlimit: number;
        resetepoch: number;
        unknown?: boolean;
    };

    // ainshrpc.RemoteInfo
    type RemoteInfo = {
        clientarch: string;
        clientos: string;
        clientversion: string;
        shell: string;
    };

    // ainshrpc.RestartBuilderAndWaitResult
    type RestartBuilderAndWaitResult = {
        success: boolean;
        errormessage?: string;
        buildoutput: string;
    };

    // ainshrpc.RpcContext
    type RpcContext = {
        sockname?: string;
        routeid: string;
        blockid?: string;
        conn?: string;
        isrouter?: boolean;
    };

    // ainshutil.RpcMessage
    type RpcMessage = {
        command?: string;
        reqid?: string;
        resid?: string;
        timeout?: number;
        route?: string;
        source?: string;
        cont?: boolean;
        cancel?: boolean;
        error?: string;
        datatype?: string;
        data?: any;
    };

    // ainshrpc.RpcOpts
    type RpcOpts = {
        timeout?: number;
        noresponse?: boolean;
        route?: string;
    };

    // ainobj.RuntimeOpts
    type RuntimeOpts = {
        termsize?: TermSize;
        winsize?: WinSize;
    };

    // ainshrpc.SecretMeta
    type SecretMeta = {
        desc: string;
        optional: boolean;
    };

    // webcmd.SetBlockTermSizeWSCommand
    type SetBlockTermSizeWSCommand = {
        wscommand: "setblocktermsize";
        blockid: string;
        termsize: TermSize;
    };

    // ainconfig.SettingsType
    type SettingsType = {
        "app:*"?: boolean;
        "app:globalhotkey"?: string;
        "app:dismissarchitecturewarning"?: boolean;
        "app:defaultnewblock"?: string;
        "app:showoverlayblocknums"?: boolean;
        "app:ctrlvpaste"?: boolean;
        "feature:waveappbuilder"?: boolean;
        "ai:*"?: boolean;
        "ai:preset"?: string;
        "ai:apitype"?: string;
        "ai:baseurl"?: string;
        "ai:apitoken"?: string;
        "ai:name"?: string;
        "ai:model"?: string;
        "ai:orgid"?: string;
        "ai:apiversion"?: string;
        "ai:maxtokens"?: number;
        "ai:timeoutms"?: number;
        "ai:proxyurl"?: string;
        "ai:fontsize"?: number;
        "ai:fixedfontsize"?: number;
        "waveai:showcloudmodes"?: boolean;
        "waveai:defaultmode"?: string;
        "ainai:showcloudmodes"?: boolean;
        "ainai:defaultmode"?: string;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:theme"?: string;
        "term:disablewebgl"?: boolean;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:gitbashpath"?: string;
        "term:scrollback"?: number;
        "term:copyonselect"?: boolean;
        "term:transparency"?: number;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "editor:inlinediff"?: boolean;
        "web:*"?: boolean;
        "web:openlinksinternally"?: boolean;
        "web:defaulturl"?: string;
        "web:defaultsearch"?: string;
        "blockheader:*"?: boolean;
        "blockheader:showblockids"?: boolean;
        "autoupdate:*"?: boolean;
        "autoupdate:enabled"?: boolean;
        "autoupdate:intervalms"?: number;
        "autoupdate:installonquit"?: boolean;
        "autoupdate:channel"?: string;
        "markdown:fontsize"?: number;
        "markdown:fixedfontsize"?: number;
        "preview:showhiddenfiles"?: boolean;
        "tab:preset"?: string;
        "widget:*"?: boolean;
        "widget:showhelp"?: boolean;
        "window:*"?: boolean;
        "window:fullscreenonlaunch"?: boolean;
        "window:transparent"?: boolean;
        "window:blur"?: boolean;
        "window:opacity"?: number;
        "window:bgcolor"?: string;
        "window:reducedmotion"?: boolean;
        "window:tilegapsize"?: number;
        "window:showmenubar"?: boolean;
        "window:nativetitlebar"?: boolean;
        "window:disablehardwareacceleration"?: boolean;
        "window:maxtabcachesize"?: number;
        "window:magnifiedblockopacity"?: number;
        "window:magnifiedblocksize"?: number;
        "window:magnifiedblockblurprimarypx"?: number;
        "window:magnifiedblockblursecondarypx"?: number;
        "window:confirmclose"?: boolean;
        "window:savelastwindow"?: boolean;
        "window:dimensions"?: string;
        "window:zoom"?: number;
        "telemetry:*"?: boolean;
        "telemetry:enabled"?: boolean;
        "conn:*"?: boolean;
        "conn:askbeforewshinstall"?: boolean;
        "conn:wshenabled"?: boolean;
        "debug:*"?: boolean;
        "debug:pprofport"?: number;
        "debug:pprofmemprofilerate"?: number;
        "tsunami:*"?: boolean;
        "tsunami:scaffoldpath"?: string;
        "tsunami:sdkreplacepath"?: string;
        "tsunami:sdkversion"?: string;
        "tsunami:gopath"?: string;
    };

    // ainobj.StickerClickOptsType
    type StickerClickOptsType = {
        sendinput?: string;
        createblock?: BlockDef;
    };

    // ainobj.StickerDisplayOptsType
    type StickerDisplayOptsType = {
        icon: string;
        imgsrc: string;
        svgblob?: string;
    };

    // ainobj.StickerType
    type StickerType = {
        stickertype: string;
        style: {[key: string]: any};
        clickopts?: StickerClickOptsType;
        display: StickerDisplayOptsType;
    };

    // ainps.SubscriptionRequest
    type SubscriptionRequest = {
        event: string;
        scopes?: string[];
        allscopes?: boolean;
    };

    // ainshrpc.SuggestionType
    type SuggestionType = {
        type: string;
        suggestionid: string;
        display: string;
        subtext?: string;
        icon?: string;
        iconcolor?: string;
        iconsrc?: string;
        matchpos?: number[];
        submatchpos?: number[];
        score?: number;
        "file:mimetype"?: string;
        "file:path"?: string;
        "file:name"?: string;
        "url:url"?: string;
    };

    // telemetrydata.TEvent
    type TEvent = {
        uuid?: string;
        ts?: number;
        tslocal?: string;
        event: string;
        props: TEventProps;
    };

    // telemetrydata.TEventProps
    type TEventProps = {
        "client:arch"?: string;
        "client:version"?: string;
        "client:initial_version"?: string;
        "client:buildtime"?: string;
        "client:osrelease"?: string;
        "client:isdev"?: boolean;
        "cohort:month"?: string;
        "cohort:isoweek"?: string;
        "autoupdate:channel"?: string;
        "autoupdate:enabled"?: boolean;
        "localshell:type"?: string;
        "localshell:version"?: string;
        "loc:countrycode"?: string;
        "loc:regioncode"?: string;
        "settings:customwidgets"?: number;
        "settings:customaipresets"?: number;
        "settings:customsettings"?: number;
        "settings:customaimodes"?: number;
        "settings:secretscount"?: number;
        "settings:transparent"?: boolean;
        "activity:activeminutes"?: number;
        "activity:fgminutes"?: number;
        "activity:openminutes"?: number;
        "activity:waveaiactiveminutes"?: number;
        "activity:waveaifgminutes"?: number;
        "activity:termcommandsrun"?: number;
        "app:firstday"?: boolean;
        "app:firstlaunch"?: boolean;
        "action:initiator"?: "keyboard" | "mouse";
        "action:type"?: string;
        "debug:panictype"?: string;
        "block:view"?: string;
        "block:controller"?: string;
        "ai:backendtype"?: string;
        "ai:local"?: boolean;
        "wsh:cmd"?: string;
        "wsh:haderror"?: boolean;
        "conn:conntype"?: string;
        "conn:wsherrorcode"?: string;
        "onboarding:feature"?: "waveai" | "magnify" | "wsh";
        "onboarding:version"?: string;
        "onboarding:githubstar"?: "already" | "star" | "later";
        "display:height"?: number;
        "display:width"?: number;
        "display:dpr"?: number;
        "display:count"?: number;
        "display:all"?: any;
        "count:blocks"?: number;
        "count:tabs"?: number;
        "count:windows"?: number;
        "count:workspaces"?: number;
        "count:sshconn"?: number;
        "count:wslconn"?: number;
        "count:views"?: {[key: string]: number};
        "waveai:apitype"?: string;
        "waveai:model"?: string;
        "waveai:chatid"?: string;
        "waveai:stepnum"?: number;
        "waveai:inputtokens"?: number;
        "waveai:outputtokens"?: number;
        "waveai:nativewebsearchcount"?: number;
        "waveai:requestcount"?: number;
        "waveai:toolusecount"?: number;
        "waveai:tooluseerrorcount"?: number;
        "waveai:tooldetail"?: {[key: string]: number};
        "waveai:premiumreq"?: number;
        "waveai:proxyreq"?: number;
        "waveai:haderror"?: boolean;
        "waveai:imagecount"?: number;
        "waveai:pdfcount"?: number;
        "waveai:textdoccount"?: number;
        "waveai:textlen"?: number;
        "waveai:firstbytems"?: number;
        "waveai:requestdurms"?: number;
        "waveai:widgetaccess"?: boolean;
        "waveai:thinkinglevel"?: string;
        "waveai:mode"?: string;
        "waveai:provider"?: string;
        "waveai:islocal"?: boolean;
        "waveai:feedback"?: "good" | "bad";
        "waveai:action"?: string;
        "ainai:feedback"?: "good" | "bad";
        $set?: TEventUserProps;
        $set_once?: TEventUserProps;
    };

    // telemetrydata.TEventUserProps
    type TEventUserProps = {
        "client:arch"?: string;
        "client:version"?: string;
        "client:initial_version"?: string;
        "client:buildtime"?: string;
        "client:osrelease"?: string;
        "client:isdev"?: boolean;
        "cohort:month"?: string;
        "cohort:isoweek"?: string;
        "autoupdate:channel"?: string;
        "autoupdate:enabled"?: boolean;
        "localshell:type"?: string;
        "localshell:version"?: string;
        "loc:countrycode"?: string;
        "loc:regioncode"?: string;
        "settings:customwidgets"?: number;
        "settings:customaipresets"?: number;
        "settings:customsettings"?: number;
        "settings:customaimodes"?: number;
        "settings:secretscount"?: number;
        "settings:transparent"?: boolean;
    };

    // ainobj.Tab
    type Tab = WaveObj & {
        name: string;
        layoutstate: string;
        blockids: string[];
    };

    // ainobj.TermSize
    type TermSize = {
        rows: number;
        cols: number;
    };

    // ainconfig.TermThemeType
    type TermThemeType = {
        "display:name": string;
        "display:order": number;
        black: string;
        red: string;
        green: string;
        yellow: string;
        blue: string;
        magenta: string;
        cyan: string;
        white: string;
        brightBlack: string;
        brightRed: string;
        brightGreen: string;
        brightYellow: string;
        brightBlue: string;
        brightMagenta: string;
        brightCyan: string;
        brightWhite: string;
        gray: string;
        cmdtext: string;
        foreground: string;
        selectionBackground: string;
        background: string;
        cursor: string;
    };

    // ainshrpc.TimeSeriesData
    type TimeSeriesData = {
        ts: number;
        values: {[key: string]: number};
    };

    // uctypes.UIChat
    type UIChat = {
        chatid: string;
        apitype: string;
        model: string;
        apiversion: string;
        messages: UIMessage[];
    };

    // ainobj.UIContext
    type UIContext = {
        windowid: string;
        activetabid: string;
    };

    // uctypes.UIMessage
    type UIMessage = {
        id: string;
        role: string;
        metadata?: any;
        parts?: UIMessagePart[];
    };

    // uctypes.UIMessagePart
    type UIMessagePart = {
        type: string;
        text?: string;
        state?: string;
        toolCallId?: string;
        input?: any;
        output?: any;
        errorText?: string;
        providerExecuted?: boolean;
        sourceId?: string;
        url?: string;
        title?: string;
        filename?: string;
        mediaType?: string;
        id?: string;
        data?: any;
        providerMetadata?: {[key: string]: any};
    };

    // userinput.UserInputRequest
    type UserInputRequest = {
        requestid: string;
        querytext: string;
        responsetype: string;
        title: string;
        markdown: boolean;
        timeoutms: number;
        checkboxmsg: string;
        publictext: boolean;
        oklabel?: string;
        cancellabel?: string;
    };

    // userinput.UserInputResponse
    type UserInputResponse = {
        type: string;
        requestid: string;
        text?: string;
        confirm?: boolean;
        errormsg?: string;
        checkboxstat?: boolean;
    };

    // vdom.VDomAsyncInitiationRequest
    type VDomAsyncInitiationRequest = {
        type: "asyncinitiationrequest";
        ts: number;
        blockid?: string;
    };

    // vdom.VDomBackendOpts
    type VDomBackendOpts = {
        closeonctrlc?: boolean;
        globalkeyboardevents?: boolean;
        globalstyles?: boolean;
    };

    // vdom.VDomBackendUpdate
    type VDomBackendUpdate = {
        type: "backendupdate";
        ts: number;
        blockid: string;
        opts?: VDomBackendOpts;
        haswork?: boolean;
        renderupdates?: VDomRenderUpdate[];
        transferelems?: VDomTransferElem[];
        statesync?: VDomStateSync[];
        refoperations?: VDomRefOperation[];
        messages?: VDomMessage[];
    };

    // vdom.VDomBinding
    type VDomBinding = {
        type: "binding";
        bind: string;
    };

    // vdom.VDomCreateContext
    type VDomCreateContext = {
        type: "createcontext";
        ts: number;
        meta?: MetaType;
        target?: VDomTarget;
        persist?: boolean;
    };

    // vdom.VDomElem
    type VDomElem = {
        waveid?: string;
        tag: string;
        props?: {[key: string]: any};
        children?: VDomElem[];
        text?: string;
    };

    // vdom.VDomEvent
    type VDomEvent = {
        waveid: string;
        eventtype: string;
        globaleventtype?: string;
        targetvalue?: string;
        targetchecked?: boolean;
        targetname?: string;
        targetid?: string;
        keydata?: WaveKeyboardEvent;
        mousedata?: WavePointerData;
    };

    // vdom.VDomFrontendUpdate
    type VDomFrontendUpdate = {
        type: "frontendupdate";
        ts: number;
        blockid: string;
        correlationid?: string;
        dispose?: boolean;
        resync?: boolean;
        rendercontext?: VDomRenderContext;
        events?: VDomEvent[];
        statesync?: VDomStateSync[];
        refupdates?: VDomRefUpdate[];
        messages?: VDomMessage[];
    };

    // vdom.VDomFunc
    type VDomFunc = {
        type: "func";
        stoppropagation?: boolean;
        preventdefault?: boolean;
        globalevent?: string;
        #keys?: string[];
    };

    // vdom.VDomMessage
    type VDomMessage = {
        messagetype: string;
        message: string;
        stacktrace?: string;
        params?: any[];
    };

    // vdom.VDomRef
    type VDomRef = {
        type: "ref";
        refid: string;
        trackposition?: boolean;
        position?: VDomRefPosition;
        hascurrent?: boolean;
    };

    // vdom.VDomRefOperation
    type VDomRefOperation = {
        refid: string;
        op: string;
        params?: any[];
        outputref?: string;
    };

    // vdom.VDomRefPosition
    type VDomRefPosition = {
        offsetheight: number;
        offsetwidth: number;
        scrollheight: number;
        scrollwidth: number;
        scrolltop: number;
        boundingclientrect: DomRect;
    };

    // vdom.VDomRefUpdate
    type VDomRefUpdate = {
        refid: string;
        hascurrent: boolean;
        position?: VDomRefPosition;
    };

    // vdom.VDomRenderContext
    type VDomRenderContext = {
        blockid: string;
        focused: boolean;
        width: number;
        height: number;
        rootrefid: string;
        background?: boolean;
    };

    // vdom.VDomRenderUpdate
    type VDomRenderUpdate = {
        updatetype: "root"|"append"|"replace"|"remove"|"insert";
        waveid?: string;
        vdomwaveid?: string;
        vdom?: VDomElem;
        index?: number;
    };

    // vdom.VDomStateSync
    type VDomStateSync = {
        atom: string;
        value: any;
    };

    // vdom.VDomTarget
    type VDomTarget = {
        newblock?: boolean;
        magnified?: boolean;
        toolbar?: VDomTargetToolbar;
    };

    // vdom.VDomTargetToolbar
    type VDomTargetToolbar = {
        toolbar: boolean;
        height?: string;
    };

    // vdom.VDomTransferElem
    type VDomTransferElem = {
        waveid?: string;
        tag: string;
        props?: {[key: string]: any};
        children?: string[];
        text?: string;
    };

    // ainshrpc.VDomUrlRequestData
    type VDomUrlRequestData = {
        method: string;
        url: string;
        headers: {[key: string]: string};
        body?: string;
    };

    // ainshrpc.VDomUrlRequestResponse
    type VDomUrlRequestResponse = {
        statuscode?: number;
        headers?: {[key: string]: string};
        body?: string;
    };

    type WSCommandType = {
        wscommand: string;
    } & ( SetBlockTermSizeWSCommand | BlockInputWSCommand | WSRpcCommand );

    // eventbus.WSEventType
    type WSEventType = {
        eventtype: string;
        oref?: string;
        data: any;
    };

    // ainps.WSFileEventData
    type WSFileEventData = {
        zoneid: string;
        filename: string;
        fileop: string;
        data64: string;
    };

    // webcmd.WSRpcCommand
    type WSRpcCommand = {
        wscommand: "rpc";
        message: RpcMessage;
    };

    // ainconfig.WatcherUpdate
    type WatcherUpdate = {
        fullconfig: FullConfigType;
    };

    // ainshrpc.WaveAIOptsType
    type WaveAIOptsType = {
        model: string;
        apitype?: string;
        apitoken: string;
        orgid?: string;
        apiversion?: string;
        baseurl?: string;
        proxyurl?: string;
        maxtokens?: number;
        maxchoices?: number;
        timeoutms?: number;
    };

    // ainshrpc.WaveAIPacketType
    type WaveAIPacketType = {
        type: string;
        model?: string;
        created?: number;
        finish_reason?: string;
        usage?: WaveAIUsageType;
        index?: number;
        text?: string;
        error?: string;
    };

    // ainshrpc.WaveAIPromptMessageType
    type WaveAIPromptMessageType = {
        role: string;
        content: string;
        name?: string;
    };

    // ainshrpc.WaveAIStreamRequest
    type WaveAIStreamRequest = {
        clientid?: string;
        opts: WaveAIOptsType;
        prompt: WaveAIPromptMessageType[];
    };

    // ainshrpc.WaveAIUsageType
    type WaveAIUsageType = {
        prompt_tokens?: number;
        completion_tokens?: number;
        total_tokens?: number;
    };

    // ainps.WaveEvent
    type WaveEvent = {
        event: string;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: any;
    };

    // filestore.WaveFile
    type WaveFile = {
        zoneid: string;
        name: string;
        opts: FileOpts;
        createdts: number;
        size: number;
        modts: number;
        meta: {[key: string]: any};
    };

    // ainshrpc.WaveInfoData
    type WaveInfoData = {
        version: string;
        clientid: string;
        buildtime: string;
        configdir: string;
        datadir: string;
    };

    // vdom.WaveKeyboardEvent
    type WaveKeyboardEvent = {
        type: "keydown"|"keyup"|"keypress"|"unknown";
        key: string;
        code: string;
        repeat?: boolean;
        location?: number;
        shift?: boolean;
        control?: boolean;
        alt?: boolean;
        meta?: boolean;
        cmd?: boolean;
        option?: boolean;
    };

    // ainshrpc.WaveNotificationOptions
    type WaveNotificationOptions = {
        title?: string;
        body?: string;
        silent?: boolean;
    };

    // ainobj.WaveObj
    type WaveObj = {
        otype: string;
        oid: string;
        version: number;
        meta: MetaType;
    };

    // ainobj.WaveObjUpdate
    type WaveObjUpdate = {
        updatetype: string;
        otype: string;
        oid: string;
        obj?: WaveObj;
    };

    // vdom.WavePointerData
    type WavePointerData = {
        button: number;
        buttons: number;
        clientx?: number;
        clienty?: number;
        pagex?: number;
        pagey?: number;
        screenx?: number;
        screeny?: number;
        movementx?: number;
        movementy?: number;
        shift?: boolean;
        control?: boolean;
        alt?: boolean;
        meta?: boolean;
        cmd?: boolean;
        option?: boolean;
    };

    // ainobj.Window
    type WaveWindow = WaveObj & {
        workspaceid: string;
        isnew?: boolean;
        pos: Point;
        winsize: WinSize;
        lastfocusts: number;
    };

    // ainconfig.WebBookmark
    type WebBookmark = {
        url: string;
        title?: string;
        icon?: string;
        iconcolor?: string;
        iconurl?: string;
        "display:order"?: number;
    };

    // service.WebCallType
    type WebCallType = {
        service: string;
        method: string;
        uicontext?: UIContext;
        args: any[];
    };

    // service.WebReturnType
    type WebReturnType = {
        success?: boolean;
        error?: string;
        data?: any;
        updates?: WaveObjUpdate[];
    };

    // ainshrpc.WebSelectorOpts
    type WebSelectorOpts = {
        all?: boolean;
        inner?: boolean;
    };

    // ainconfig.WidgetConfigType
    type WidgetConfigType = {
        "display:order"?: number;
        "display:hidden"?: boolean;
        icon?: string;
        color?: string;
        label?: string;
        description?: string;
        magnified?: boolean;
        blockdef: BlockDef;
    };

    // ainobj.WinSize
    type WinSize = {
        width: number;
        height: number;
    };

    // ainobj.Workspace
    type Workspace = WaveObj & {
        name?: string;
        icon?: string;
        color?: string;
        tabids: string[];
        activetabid: string;
    };

    // ainshrpc.WorkspaceInfoData
    type WorkspaceInfoData = {
        windowid: string;
        workspacedata: Workspace;
    };

    // ainobj.WorkspaceListEntry
    type WorkspaceListEntry = {
        workspaceid: string;
        windowid: string;
    };

    // ainshrpc.WshServerCommandMeta
    type WshServerCommandMeta = {
        commandtype: string;
    };

}

export {}
